export const constants = {
    CONNECT_WALLET: "CONNECT_WALLET",
    LOADING: "LOADING",
    SET_PAGE_ERROR: "SET_PAGE_ERROR",
    SET_LOADING: "SET_LOADING",
    SET_PAGE_IS_READY: "SET_PAGE_IS_READY",
    SET_USD_TO_SOL: "SET_USD_TO_SOL",
    GET_VALIDATORS: "GET_VALIDATORS",
    APP_MODE: "APP_MODE"
}


export const collectionActions = {
    "SET_MOST_RATED_COLLECTIONS": "SET_MOST_RATED_COLLECTIONS",
    "SET_COLLECTIONS": "SET_COLLECTIONS",
    "GET_COLLECTIONS_LOADING": "GET_COLLECTIONS_LOADING",
    "STOP_COLLECTIONS_LOADING": "STOP_COLLECTIONS_LOADING"
}


export const validatorsActions = {
    "SET_TOP_VALIDATORS": "SET_TOP_VALIDATORS",
    "SET_VALIDATORS": "SET_VALIDATORS",
    "SET_VALIDATORS_LOADING": "SET_VALIDATORS_LOADING",
    "STOP_VALIDATORS_LOADING": "STOP_VALIDATORS_LOADING"
}