export const constants = {
    CONNECT_WALLET: "CONNECT_WALLET",
    LOADING: "LOADING",
    GET_VALIDATORS: "GET_VALIDATORS",
    APP_MODE: "APP_MODE"
}


export const collectionActions = {
    "SET_MOST_RATED_COLLECTIONS": "SET_MOST_RATED_COLLECTIONS",
    "SET_COLLECTIONS": "SET_COLLECTIONS",
    "GET_COLLECTIONS_LOADING": "GET_COLLECTIONS_LOADING",
    "STOP_COLLECTIONS_LOADING": "STOP_COLLECTIONS_LOADING"
}


export const validatorsActions = {
    "TOP_VALIDATORS": "TOP_VALIDATORS",
    "SET_VALIDATORS": "SET_VALIDATORS",
    "SET_VALIDATORS_LOADING": "SET_VALIDATORS_LOADING",
    "STOP_VALIDATORS_LOADING": "STOP_VALIDATORS_LOADING"
}